// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWx1y1gP2fdZlY6zkY6KaIQxhTezVfpAw',
    appId: '1:1022366886887:web:2b436fd7cf30c1444d2b42',
    messagingSenderId: '1022366886887',
    projectId: 'uaskel6-6ddac',
    authDomain: 'uaskel6-6ddac.firebaseapp.com',
    storageBucket: 'uaskel6-6ddac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh7qPCy9HGzjv3u6qw5X7-OWiVlH_XeDM',
    appId: '1:1022366886887:android:e691c5ccc458fcdd4d2b42',
    messagingSenderId: '1022366886887',
    projectId: 'uaskel6-6ddac',
    storageBucket: 'uaskel6-6ddac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDjjDDUv3HuJHzrI8Q5BgYUikJL-_5Mfw',
    appId: '1:1022366886887:ios:299914d3ca7d82794d2b42',
    messagingSenderId: '1022366886887',
    projectId: 'uaskel6-6ddac',
    storageBucket: 'uaskel6-6ddac.appspot.com',
    iosClientId: '1022366886887-rs4m63qh4jp6jtb4mqdnmlibu7mhvusi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDjjDDUv3HuJHzrI8Q5BgYUikJL-_5Mfw',
    appId: '1:1022366886887:ios:299914d3ca7d82794d2b42',
    messagingSenderId: '1022366886887',
    projectId: 'uaskel6-6ddac',
    storageBucket: 'uaskel6-6ddac.appspot.com',
    iosClientId: '1022366886887-rs4m63qh4jp6jtb4mqdnmlibu7mhvusi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryFirebase',
  );
}
